"""add discount_targets table

Revision ID: 2227ddfb6d74
Revises: 55e6ce3431d3
Create Date: 2026-04-20 15:37:03.765258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2227ddfb6d74'
down_revision: Union[str, Sequence[str], None] = '55e6ce3431d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('discount_id', sa.Uuid(), nullable=False),
    sa.Column('target_type', sa.Enum('CATEGORY', 'PRODUCT', name='discounttargettype'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type')
    )
    op.create_index(op.f('ix_discount_targets_discount_id'), 'discount_targets', ['discount_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_discount_targets_discount_id'), table_name='discount_targets')
    op.drop_table('discount_targets')
    # ### end Alembic commands ###
