"""add ordercode to order table

Revision ID: 4022b8be2677
Revises: ff7300d29fad
Create Date: 2026-05-18 11:32:23.474728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4022b8be2677'
down_revision: Union[str, Sequence[str], None] = 'ff7300d29fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_orders_order_code'), 'orders', ['order_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_order_code'), table_name='orders')
    op.drop_column('orders', 'order_code')
    # ### end Alembic commands ###
