"""remove unquie of sku in product_variant table

Revision ID: 698a8e60086f
Revises: 6f8a5e41d3bf
Create Date: 2026-04-17 11:19:32.622978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '698a8e60086f'
down_revision: Union[str, Sequence[str], None] = '6f8a5e41d3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_variants_sku_key'), 'product_variants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('product_variants_sku_key'), 'product_variants', ['sku'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
