"""add status to discounts table

Revision ID: 87d0bbd90232
Revises: 2227ddfb6d74
Create Date: 2026-04-20 16:25:50.446926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '87d0bbd90232'
down_revision: Union[str, Sequence[str], None] = '2227ddfb6d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


discount_status = sa.Enum('ACTIVE', 'SCHEDULED', 'PAUSED', 'ENDED', name='discountstatus')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    discount_status.create(op.get_bind(), checkfirst=True)
    op.add_column('discounts', sa.Column('status', discount_status, nullable=False))
    op.drop_column('discounts', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discounts', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('discounts', 'status')
    # ### end Alembic commands ###
