"""change column name in cart_items table

Revision ID: 8df01da05eee
Revises: e0a7c107f032
Create Date: 2026-04-24 11:13:56.828824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8df01da05eee'
down_revision: Union[str, Sequence[str], None] = 'e0a7c107f032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('cart_items', 'quanlity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('quanlity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cart_items', 'quantity')
    # ### end Alembic commands ###
