"""drop unquie target_type in discount_targets table

Revision ID: be776a7bcf13
Revises: 87d0bbd90232
Create Date: 2026-04-21 11:24:01.676589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'be776a7bcf13'
down_revision: Union[str, Sequence[str], None] = '87d0bbd90232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('discount_targets_target_type_key'), 'discount_targets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('discount_targets_target_type_key'), 'discount_targets', ['target_type'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
