"""add level field to category table

Revision ID: ca03972d9918
Revises: bf611da1baf8
Create Date: 2026-04-14 13:11:30.719483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ca03972d9918'
down_revision: Union[str, Sequence[str], None] = 'bf611da1baf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


category_level_enum = postgresql.ENUM(
    "ROOT", "CHILD", "LEAF",
    name="categorylevel"
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    category_level_enum.create(op.get_bind()) 
    
    op.add_column('categories', sa.Column('level', sa.Enum('ROOT', 'CHILD', 'LEAF', name='categorylevel'), nullable=False, server_default='LEAF'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'level')
    # ### end Alembic commands ###
