"""update constraint in cart_items table

Revision ID: e0a7c107f032
Revises: a95bc11992ce
Create Date: 2026-04-24 09:21:04.567089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e0a7c107f032'
down_revision: Union[str, Sequence[str], None] = 'a95bc11992ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.drop_index(op.f('ix_cart_items_variant_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_variant_id'), 'cart_items', ['variant_id'], unique=False)
    op.create_unique_constraint(None, 'cart_items', ['cart_id', 'variant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='unique')
    op.drop_index(op.f('ix_cart_items_variant_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_variant_id'), 'cart_items', ['variant_id'], unique=True)
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=True)
    # ### end Alembic commands ###
